site_name: Video-CLIP
site_author: Unakar
site_description: >-
  Adapting CLIP for Cross-modal Video Understanding

copyright: Copyright &copy; 2024 Xie Tian

# Page tree
nav:
  - Home: index.md
  - Project docs:
    - FrameworkDesign: project_docs/项目设计.md
  - Survey: 
    - CLIP4clip: survey/CLIP4clip.md
  - Tasks:
    - 第一周: Tasks/第一周任务.md
    


theme:
  name: material
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: indigo
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
     - content.code.select
    # - content.footnote.tooltips
     - content.tabs.link
    - content.tooltips
     - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate


repo_name: Unakar/Video-CLIP
repo_url: https://github.com/Unakar/Video-CLIP



